services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./_docker_volumes/postgres:/data/dump
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
